# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('dates_attended', models.DurationField(default=datetime.timedelta(0))),
                ('major', models.CharField(max_length=200)),
                ('GPA', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('clubs', models.CharField(max_length=1000)),
                ('societies', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='time_period',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Company'),
        ),
    ]
