# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20160727_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='ingredient', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='prep',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='direction',
            name='order',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(blank=True, verbose_name='Ingredient amount'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
